name: Workflow test 

on: 
  push:
  repository_dispatch:

jobs: 
  steps: 
    - name: print version ansible 
      run: ansible --versionb

    - name: print version ansible-playbook 
      run: ansible-playbook --version

  
