name: Workflow test 

on: 
  push:
  repository_dispatch:

jobs: 
  labo:
    name: experiment ansible version
    runs-on: ubuntu-latest
    steps: 
      - name: print version ansible 
        run: ansible --version

      - name: print version ansible-playbook 
        run: ansible-playbook --version

  
